import { Fragment } from "react";
import { Button, Container, TextField, Typography } from "@mui/material";

import Head from "next/head";
import BasicTable from "@/components/Table/BasicTable";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{
          padding: "2rem",
        }}
      >
        <TextField
          variant="outlined"
          label="Cari Data"
          placeholder="Cari Data...."
        />
        <BasicTable />
      </Container>
    </Fragment>
  );
}
